# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-08 06:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiderBar',
            new_name='SideBar',
        ),
    ]
